// The code generator turns the checked tree into one JavaScript ES module.
//
// Output shape:
//
//   export const $url = import.meta.url;
//   export function create($rt)
//   {
//     ...helpers and commands taken from the runtime...
//     ...Types, Globals, arrays, Data...
//     function fn_update() { ... }
//     function $main() { ... }
//     return { main: $main, update: fn_update, draw: null };
//   }
//   export const $map = { ... };   // JS line -> .pb line, for error reports
//
// Everything is plain synchronous JavaScript: the host owns the frame loop
// and calls update/draw, so no statement ever has to wait. Ints stay 32-bit
// by wrapping every Int operation (`| 0`, Math.imul); names are prefixed by
// kind (l_ local, g_ global, d_ Dim array, fn_ function, T_ Type, f_ field)
// so user names never clash with JavaScript or with each other.

import { INT, FLOAT, STRING, NULL, zeroValue } from './types.js';

export function generate(sem, options = {})
{
  return new Generator(sem, options).run();
}

class Generator
{
  constructor(sem, options)
  {
    this.sem = sem;
    this.source = options.file || 'main.pb';
    this.lines = [];          // { text, pos }
    this.indent = 0;
    this.pos = null;
    this.helpers = new Set();
    this.commands = new Map();
  }

  // ---------------------------------------------------------------- output

  emit(text, pos = this.pos)
  {
    this.lines.push({ text: text ? '  '.repeat(this.indent) + text : '', pos });
  }

  open(header, pos)
  {
    if (header !== null) this.emit(header, pos);
    this.emit('{', pos);
    this.indent++;
  }

  close(tail = '}')
  {
    this.indent--;
    this.emit(tail);
  }

  helper(name)
  {
    this.helpers.add(name);
    return name;
  }

  command(cmd)
  {
    this.commands.set(cmd.key, 'c_' + cmd.key);
    return 'c_' + cmd.key;
  }

  // ---------------------------------------------------------------- module

  run()
  {
    const sem = this.sem;

    // The body is generated first so we know which helpers it used; the
    // header that imports them is spliced in front afterwards.
    const header = this.lines;
    this.lines = [];
    this.indent = 1;
    this.pos = null;

    for (const t of sem.types) this.typeDecl(t);
    for (const g of sem.globals)
    {
      if (g.kind !== 'global') continue;
      const init = g.vector ? this.newVector(g.type, g.vector) : literalCode(g.type, zeroValue(g.type));
      this.emit(`let ${g.js} = ${init};`, g.pos);
    }
    for (const a of sem.arrays)
    {
      this.emit(`let ${a.js} = ${this.helper('$dim')}(${kindCode(a.elem)}, [], ${JSON.stringify(a.name)});`);
    }
    if (sem.data.length)
    {
      const values = sem.data.map((d) => literalCode(d.type, d.value)).join(', ');
      const kinds = sem.data.map((d) => kindCode(d.type)).join(', ');
      this.emit(`$rt.setData([${values}], [${kinds}]);`);
    }
    for (const fn of sem.functions) this.functionDecl(fn);
    this.mainDecl(sem.main);
    this.pos = null;
    const update = this.frameEntry(sem.update);
    const draw = this.frameEntry(sem.draw);
    this.emit('');
    this.emit(`return { main: $main, update: ${update}, draw: ${draw} };`);
    this.indent = 0;
    this.emit('}');
    const body = this.lines;

    this.lines = header;
    this.indent = 0;
    this.pos = null;
    this.emit(`// Generated by the PolyBasic compiler from ${this.source.replace(/[\r\n]/g, " ")}. Do not edit.`);
    this.emit('export const $url = import.meta.url;');
    this.emit('');
    this.emit('export function create($rt)');
    this.emit('{');
    this.indent = 1;
    if (this.helpers.size) this.emit(`const { ${[...this.helpers].sort().join(', ')} } = $rt.helpers;`);
    if (this.commands.size)
    {
      const list = [...this.commands].sort().map(([key, js]) => `${key}: ${js}`).join(', ');
      this.emit(`const { ${list} } = $rt.commands;`);
    }
    this.lines.push(...body);

    const files = this.sem.files;
    const fileIndex = new Map(files.map((f, i) => [f, i]));
    const lineMap = this.lines.map((l) => (l.pos ? l.pos.line : 0));
    const fileMap = this.lines.map((l) => (l.pos ? fileIndex.get(l.pos.file) || 0 : 0));
    let js = this.lines.map((l) => l.text).join('\n');
    js += '\n\n// Maps each line of this file back to the PolyBasic source, for error reports.\n';
    js += `export const $map = { files: ${JSON.stringify(files)}, lines: ${JSON.stringify(lineMap)}`;
    js += files.length > 1 ? `, fileOf: ${JSON.stringify(fileMap)} };\n` : ' };\n';
    return js;
  }

  // The host calls Update and Draw with no arguments; parameters with
  // defaults (the only kind they may have) get their values here.
  frameEntry(fn)
  {
    if (!fn) return 'null';
    if (!fn.params.length) return fn.js;
    const defaults = fn.params.map((p) => this.expr(p.def)).join(', ');
    return `() => ${fn.js}(${defaults})`;
  }

  typeDecl(t)
  {
    this.pos = null;
    this.emit('');
    this.open(`class ${t.js}`, t.node.pos);
    this.open('constructor()');
    for (const f of t.fields.values())
    {
      const init = f.vector ? this.newVector(f.type, f.vector) : literalCode(f.type, zeroValue(f.type));
      this.emit(`this.${f.js} = ${init};`);
    }
    // Links of the Type's object list (see runtime `typeList`).
    this.emit('this.$prev = null;');
    this.emit('this.$next = null;');
    this.emit('this.$alive = true;');
    this.close();
    this.close();
    this.emit(`const ${t.list} = $rt.typeList(${t.js}, ${JSON.stringify(t.name)});`);
  }

  newVector(type, size)
  {
    return `${this.helper('$vec')}(${kindCode(type)}, ${size})`;
  }

  functionDecl(fn)
  {
    this.pos = null;
    this.emit('');
    const params = fn.params.map((p) => p.js).join(', ');
    this.open(`function ${fn.js}(${params})`, fn.node.pos);
    this.localDecls(fn.locals);
    this.block(fn.body);
    if (!endsWithReturn(fn.body)) this.emit(`return ${literalCode(fn.ret, zeroValue(fn.ret))};`, fn.node.endPos);
    this.close();
  }

  mainDecl(main)
  {
    this.pos = null;
    this.emit('');
    this.open('function $main()', null);
    this.localDecls(main.locals);
    this.block(main.body);
    this.close();
  }

  localDecls(locals)
  {
    for (const d of locals)
    {
      const init = d.vector ? this.newVector(d.type, d.vector) : literalCode(d.type, zeroValue(d.type));
      this.emit(`let ${d.js} = ${init};`);
    }
  }

  // ------------------------------------------------------------ statements

  block(list)
  {
    for (const s of list) this.statement(s);
  }

  statement(s)
  {
    this.pos = s.pos;
    switch (s.kind)
    {
      case 'assign':
        this.emit(`${this.target(s.target)} = ${bare(this.expr(s.expr))};`);
        return;
      case 'callStmt':
        this.emit(`${bare(this.expr(s.call))};`);
        return;
      case 'if':
        this.ifChain(s, 'if');
        return;
      case 'while':
        this.open(`while (${bare(this.cond(s.cond))})`);
        this.block(s.body);
        this.close();
        return;
      case 'repeat':
        if (!s.cond)
        {
          this.open('for (;;)');
          this.block(s.body);
          this.close();
          return;
        }
        this.open('do');
        this.block(s.body);
        this.pos = s.cond.pos;
        this.close(`}`);
        this.emit(`while (!(${this.cond(s.cond)}));`);
        return;
      case 'for':
        this.forLoop(s);
        return;
      case 'forEach':
      {
        const v = this.target(s.variable);
        this.open(`for (${v} = ${s.struct.list}.first; ${v} !== null; ${v} = ${this.helper('$next')}(${v}))`);
        this.block(s.body);
        this.close();
        return;
      }
      case 'select':
        this.select(s);
        return;
      case 'exit':
        this.emit('break;');
        return;
      case 'return':
        this.emit(`return ${bare(this.expr(s.expr))};`);
        return;
      case 'end':
        this.emit(`${this.helper('$end')}();`);
        return;
      case 'delete':
        this.emit(`${this.helper('$delete')}(${this.expr(s.expr)});`);
        return;
      case 'deleteEach':
        this.emit(`${this.helper('$deleteEach')}(${s.struct.list});`);
        return;
      case 'insert':
        this.emit(`${this.helper('$insert')}(${this.expr(s.expr)}, ${this.expr(s.target)}, ${s.before});`);
        return;
      case 'read':
      {
        const reader = s.target.type === INT ? '$readInt' : s.target.type === FLOAT ? '$readFloat' : '$readString';
        this.emit(`${this.target(s.target)} = ${this.helper(reader)}();`);
        return;
      }
      case 'restore':
        this.emit('$rt.restore();');
        return;
      case 'dim':
        for (const d of s.dims)
        {
          const sizes = d.sizes.map((e) => this.expr(e)).join(', ');
          this.emit(`${d.array.js} = ${this.helper('$dim')}(${kindCode(d.array.elem)}, [${sizes}], ${JSON.stringify(d.array.name)});`);
        }
        return;
      case 'local':
        for (const d of s.decls)
        {
          const decl = d.decl;
          let value;
          if (decl.vector) value = this.newVector(decl.type, decl.vector);
          else value = d.init ? this.expr(d.init) : literalCode(decl.type, zeroValue(decl.type));
          this.emit(`${decl.js} = ${value};`, d.pos);
        }
        return;
      case 'global':
        for (const d of s.decls)
        {
          if (d.init) this.emit(`${d.decl.js} = ${this.expr(d.init)};`, d.pos);
        }
        return;
    }
    throw new Error('codegen: unknown statement ' + s.kind);
  }

  ifChain(s, keyword)
  {
    this.pos = s.pos;
    this.open(`${keyword} (${bare(this.cond(s.cond))})`);
    this.block(s.thenBody);
    this.close();
    if (!s.elseBody) return;
    if (s.elseBody.length === 1 && s.elseBody[0].kind === 'if')
    {
      this.ifChain(s.elseBody[0], 'else if');
      return;
    }
    this.open('else');
    this.block(s.elseBody);
    this.close();
  }

  // `To` is re-evaluated on every pass (so a loop can grow its own limit),
  // the Step is a constant, so the direction of the test is known here.
  forLoop(s)
  {
    const v = this.target(s.variable);
    const up = s.step.value > 0;
    const to = this.expr(s.to);
    let step;
    if (s.variable.type === INT) step = `${v} = (${v} + ${s.step.value}) | 0`;
    else step = `${v} += ${literalCode(FLOAT, s.step.value)}`;
    this.open(`for (${v} = ${this.expr(s.from)}; ${v} ${up ? '<=' : '>='} ${to}; ${step})`);
    this.block(s.body);
    this.close();
  }

  select(s)
  {
    this.emit(`const ${s.temp} = ${this.expr(s.expr)};`);
    let first = true;
    for (const c of s.cases)
    {
      this.pos = c.pos;
      const test = c.values.map((v) => `${s.temp} === ${this.expr(v)}`).join(' || ');
      this.open(`${first ? 'if' : 'else if'} (${test})`);
      this.block(c.body);
      this.close();
      first = false;
    }
    if (s.defaultBody)
    {
      if (first)
      {
        this.block(s.defaultBody);
        return;
      }
      this.open('else');
      this.block(s.defaultBody);
      this.close();
    }
  }

  // ---------------------------------------------------------- expressions

  // Assignable places.
  target(v)
  {
    switch (v.kind)
    {
      case 'var':
        return v.decl.js;
      case 'index':
        return this.indexCode(v);
      case 'field':
        return `${this.helper('$obj')}(${this.expr(v.object)}).${v.field.js}`;
      case 'element':
        return `${this.target(v.base)}[${this.helper('$ix')}(${this.expr(v.index)}, ${v.size})]`;
    }
    throw new Error('codegen: not assignable ' + v.kind);
  }

  indexCode(v)
  {
    const a = v.array.js;
    const idx = v.indices.map((e) => this.expr(e));
    if (idx.length === 1) return `${a}.data[${this.helper('$ix1')}(${a}, ${idx[0]})]`;
    if (idx.length === 2) return `${a}.data[${this.helper('$ix2')}(${a}, ${idx[0]}, ${idx[1]})]`;
    return `${a}.data[${this.helper('$ixn')}(${a}, [${idx.join(', ')}])]`;
  }

  expr(e)
  {
    switch (e.kind)
    {
      case 'int':
      case 'float':
      case 'string':
        return literalCode(e.type, e.value);
      case 'null':
        return 'null';
      case 'var':
      case 'index':
      case 'field':
      case 'element':
        return this.target(e);
      case 'cast':
        return this.cast(e);
      case 'unary':
        if (e.op === '~') return `(~${this.expr(e.expr)})`;
        return e.type === INT ? `((-${this.expr(e.expr)}) | 0)` : `(-${this.expr(e.expr)})`;
      case 'not':
        return `(${this.notTest(e)} ? 1 : 0)`;
      case 'binary':
        return this.binary(e);
      case 'call':
        return this.call(e);
      case 'special':
        return this.special(e);
      case 'new':
        return `${this.helper('$new')}(new ${e.struct.js}())`;
      case 'first':
        return `${e.struct.list}.first`;
      case 'last':
        return `${e.struct.list}.last`;
      case 'before':
        return `${this.helper('$before')}(${this.expr(e.expr)})`;
      case 'after':
        return `${this.helper('$after')}(${this.expr(e.expr)})`;
    }
    throw new Error('codegen: unknown expression ' + e.kind);
  }

  cast(e)
  {
    const from = e.expr.type;
    const inner = this.expr(e.expr);
    if (e.type === FLOAT && from === INT) return inner;
    if (e.type === STRING) return from === INT ? `("" + ${inner})` : `${this.helper('$fstr')}(${inner})`;
    if (e.type === INT) return from === FLOAT ? `${this.helper('$f2i')}(${inner})` : `${this.helper('$s2i')}(${inner})`;
    if (e.type === FLOAT) return `${this.helper('$s2f')}(${inner})`;
    throw new Error('codegen: bad cast');
  }

  binary(e)
  {
    const op = e.op;
    if (isComparison(op)) return `(${this.compare(e)} ? 1 : 0)`;
    const l = this.expr(e.left);
    const r = this.expr(e.right);
    if (e.type === INT)
    {
      switch (op)
      {
        case '+': return `((${l} + ${r}) | 0)`;
        case '-': return `((${l} - ${r}) | 0)`;
        case '*': return `Math.imul(${l}, ${r})`;
        // A constant divisor is never 0 (the checker rejects that), so the
        // zero check can be skipped.
        case '/': return e.right.kind === 'int' ? `((${l} / ${r}) | 0)` : `${this.helper('$idiv')}(${l}, ${r})`;
        case 'mod': return e.right.kind === 'int' ? `((${l} % ${r}) | 0)` : `${this.helper('$imod')}(${l}, ${r})`;
        case 'and': return `(${l} & ${r})`;
        case 'or': return `(${l} | ${r})`;
        case 'xor': return `(${l} ^ ${r})`;
        case 'shl': return `(${l} << ${r})`;
        case 'shr': return `((${l} >>> ${r}) | 0)`;
        case 'sar': return `(${l} >> ${r})`;
      }
    }
    if (op === '^') return `Math.pow(${l}, ${r})`;
    if (op === 'mod') return `(${l} % ${r})`;
    return `(${l} ${op} ${r})`;
  }

  // A comparison as a JavaScript boolean.
  compare(e)
  {
    const l = this.expr(e.left);
    const r = this.expr(e.right);
    if (e.opType.kind === 'struct')
    {
      // Deleted objects count as Null, so comparisons go through a helper.
      let test;
      if (e.left.type === NULL) test = `${this.helper('$isNull')}(${r})`;
      else if (e.right.type === NULL) test = `${this.helper('$isNull')}(${l})`;
      else test = `${this.helper('$same')}(${l}, ${r})`;
      return e.op === '=' ? test : `!${test}`;
    }
    const js = { '=': '===', '<>': '!==', '<': '<', '>': '>', '<=': '<=', '>=': '>=' }[e.op];
    return `${l} ${js} ${r}`;
  }

  notTest(e)
  {
    const inner = e.expr;
    if (isLogical(inner)) return `!(${this.cond(inner)})`;
    if (inner.type.kind === 'struct') return `${this.helper('$isNull')}(${this.expr(inner)})`;
    if (inner.type === STRING) return `${this.expr(inner)} === ""`;
    return `${this.expr(inner)} === 0`;
  }

  // An expression used as a condition (If, While, Until). Comparisons and
  // Not become JavaScript booleans; And/Or of comparisons avoid building
  // 0/1 integers. The right side of And/Or is always evaluated, as in
  // Blitz, unless it is free of side effects and errors, where skipping it
  // cannot be noticed.
  cond(e)
  {
    if (e.kind === 'binary' && isComparison(e.op)) return this.compare(e);
    if (e.kind === 'not') return this.notTest(e);
    if (e.kind === 'binary' && (e.op === 'and' || e.op === 'or') && isLogical(e.left) && isLogical(e.right))
    {
      const l = this.cond(e.left);
      const r = this.cond(e.right);
      if (isPure(e.right)) return `(${l}) ${e.op === 'and' ? '&&' : '||'} (${r})`;
      return `((${l}) ${e.op === 'and' ? '&' : '|'} (${r}))`;
    }
    if (e.type.kind === 'struct') return `!${this.helper('$isNull')}(${this.expr(e)})`;
    return `${this.expr(e)} !== 0`;
  }

  call(e)
  {
    const args = e.args.map((a) => bare(this.expr(a)));
    if (e.fn) return `${e.fn.js}(${args.join(', ')})`;
    if (e.cmd.inline) return e.cmd.inline.replace(/\$(\d)/g, (m, i) => wrap(args[Number(i)]));
    return `${this.command(e.cmd)}(${args.join(', ')})`;
  }

  special(e)
  {
    const args = e.args.map((a) => this.expr(a));
    const int = e.type === INT;
    switch (e.name)
    {
      case 'abs': return int ? `(Math.abs(${args[0]}) | 0)` : `Math.abs(${args[0]})`;
      case 'sgn': return `Math.sign(${args[0]})`;
      case 'min': return `Math.min(${args[0]}, ${args[1]})`;
      case 'max': return `Math.max(${args[0]}, ${args[1]})`;
    }
    throw new Error('codegen: unknown special ' + e.name);
  }
}

function isComparison(op)
{
  return op === '=' || op === '<>' || op === '<' || op === '>' || op === '<=' || op === '>=';
}

// Expressions whose value is always 0 or 1.
function isLogical(e)
{
  if (e.kind === 'not') return true;
  if (e.kind !== 'binary') return false;
  if (isComparison(e.op)) return true;
  return (e.op === 'and' || e.op === 'or') && isLogical(e.left) && isLogical(e.right);
}

// Side-effect free and cannot raise a runtime error.
function isPure(e)
{
  switch (e.kind)
  {
    case 'int':
    case 'float':
    case 'string':
    case 'null':
    case 'var':
      return true;
    case 'cast':
    case 'unary':
    case 'not':
      return isPure(e.expr);
    case 'binary':
      if (e.type === INT && (e.op === '/' || e.op === 'mod') && e.right.kind !== 'int') return false;
      return isPure(e.left) && isPure(e.right);
    default:
      return false;
  }
}

function endsWithReturn(body)
{
  return body.length > 0 && body[body.length - 1].kind === 'return';
}

// Drops one pair of brackets around a whole expression, where the context
// (an argument, the right side of `=`) already delimits it.
function bare(code)
{
  if (code[0] !== '(' || code[code.length - 1] !== ')') return code;
  let depth = 0;
  let inString = false;
  for (let i = 0; i < code.length; i++)
  {
    const c = code[i];
    if (inString)
    {
      if (c === '\\') i++;
      else if (c === '"') inString = false;
      continue;
    }
    if (c === '"') inString = true;
    else if (c === '(') depth++;
    else if (c === ')' && --depth === 0 && i < code.length - 1) return code;
  }
  return code.slice(1, -1);
}

function wrap(code)
{
  return /^[\w$.]+$/.test(code) ? code : `(${code})`;
}

function kindCode(type)
{
  if (type === INT) return '"int"';
  if (type === FLOAT) return '"float"';
  if (type === STRING) return '"string"';
  return '"object"';
}

export function literalCode(type, value)
{
  if (value === null) return 'null';
  if (type === STRING) return JSON.stringify(value);
  if (value !== value) return 'NaN';
  if (value === Infinity) return 'Infinity';
  if (value === -Infinity) return '(-Infinity)';
  if (Object.is(value, -0)) return '(-0)';
  return value < 0 ? `(${value})` : String(value);
}
